# reference model
model_init: model_init2.txt

# wave type: rayleigh or love
wave_type: rayleigh

# half_width for vs, so the bounds of vs:
# [vs_init - half_width, vs_init + half_width]
init_half_width: 0.4
inv_half_width: 0.8

# method of generating initial model
# ascend or random
init_method: random

empirical_relation: brocher

# data
# column 1 | column 2 | column 3
# freq(Hz) | phase velocity (km/s) | mode (start from 0)
dir_data: data
# data: roots.txt
# weights of mode used for inversion
weights_mode: 
  0: 4.0
  1: 1.0
  2: 1.0
  3: 1.0

# regularization
# exp, tr1, tr0, tr2
reg_method: exp

# regularization
smooth:
  factor: 3.0e-2
  zmin: 0.0
  zmax: 100.0
  dmin: 10.0
  dmax: 30.0

# logging
file_logging: record.log

# output
dir_output: inversion


  #option_bfgs:
  #    gtol: 1.0e-8
  #    ftol: 1.0e-10

plot:
    percentage_show: 50
    zmax: 130
    vs_lim: [2.0, 5.0]
    model_data: model_data.txt

l-curve:
  dir_out: L-curve
  # 10^a
  amin: -4.0
  amax: 0.0
  na: 20
